---
title: "dietary models"
author: "LA"
date: "2024-03-25"
output: html_document
---
```{r}
library(dplyr)
library(haven)
library(readr)
library(dietaryindex)
library(nhanesR)
```

```{r}
getwd()
setwd("F:/NHANES_combined")
```

```{r}
load("NHANES_20052006.rda")## NHANES 2005-2006
load("NHANES_20072008.rda")## NHANES 2007-2008
load("NHANES_20092010.rda")## NHANES 2009-2010
load("NHANES_20112012.rda")## NHANES 2011-2012
load("NHANES_20132014.rda")## NHANES 2013-2014
load("NHANES_20152016.rda")## NHANES 2015-2016
```

#aMED
```{r}
MED1=MED_NHANES_FPED(FPED_PATH=NHANES_20052006$FPED, NUTRIENT_PATH=NHANES_20052006$NUTRIENT, DEMO_PATH=NHANES_20052006$DEMO, FPED_PATH2=NHANES_20052006$FPED2, NUTRIENT_PATH2=NHANES_20052006$NUTRIENT2) 
MED2=MED_NHANES_FPED(FPED_PATH=NHANES_20072008$FPED, NUTRIENT_PATH=NHANES_20072008$NUTRIENT, DEMO_PATH=NHANES_20072008$DEMO, FPED_PATH2=NHANES_20072008$FPED2, NUTRIENT_PATH2=NHANES_20072008$NUTRIENT2)
MED3=MED_NHANES_FPED(FPED_PATH=NHANES_20092010$FPED, NUTRIENT_PATH=NHANES_20092010$NUTRIENT, DEMO_PATH=NHANES_20092010$DEMO, FPED_PATH2=NHANES_20092010$FPED2, NUTRIENT_PATH2=NHANES_20092010$NUTRIENT2)
MED4=MED_NHANES_FPED(FPED_PATH=NHANES_20112012$FPED, NUTRIENT_PATH=NHANES_20112012$NUTRIENT, DEMO_PATH=NHANES_20112012$DEMO, FPED_PATH2=NHANES_20112012$FPED2, NUTRIENT_PATH2=NHANES_20112012$NUTRIENT2)
MED5=MED_NHANES_FPED(FPED_PATH=NHANES_20132014$FPED, NUTRIENT_PATH=NHANES_20132014$NUTRIENT, DEMO_PATH=NHANES_20132014$DEMO, FPED_PATH2=NHANES_20132014$FPED2, NUTRIENT_PATH2=NHANES_20132014$NUTRIENT2)
MED6=MED_NHANES_FPED(FPED_PATH=NHANES_20152016$FPED, NUTRIENT_PATH=NHANES_20152016$NUTRIENT, DEMO_PATH=NHANES_20152016$DEMO, FPED_PATH2=NHANES_20152016$FPED2, NUTRIENT_PATH2=NHANES_20152016$NUTRIENT2)

```

#MED数据合并
```{r}
MED <- Full_Join(MED1, MED2, MED3, MED4, MED5, MED6, 
                 by = c("SEQN","MED_ALL"), 
                 cat = TRUE, 
                 inspect = NULL)
    
MED <- select_col(MED,c('SEQN','MED_ALL'))
```

#AHEI
```{r}
AHEI1 = AHEI_NHANES_FPED(NHANES_20052006$FPED_IND, NHANES_20052006$NUTRIENT_IND, NHANES_20052006$FPED_IND2, NHANES_20052006$NUTRIENT_IND2)
AHEI2 = AHEI_NHANES_FPED(NHANES_20072008$FPED_IND, NHANES_20072008$NUTRIENT_IND, NHANES_20072008$FPED_IND2, NHANES_20072008$NUTRIENT_IND2)
AHEI3 = AHEI_NHANES_FPED(NHANES_20092010$FPED_IND, NHANES_20092010$NUTRIENT_IND, NHANES_20092010$FPED_IND2, NHANES_20092010$NUTRIENT_IND2)
AHEI4 = AHEI_NHANES_FPED(NHANES_20112012$FPED_IND, NHANES_20112012$NUTRIENT_IND, NHANES_20112012$FPED_IND2, NHANES_20112012$NUTRIENT_IND2)
AHEI5 = AHEI_NHANES_FPED(NHANES_20132014$FPED_IND, NHANES_20132014$NUTRIENT_IND, NHANES_20132014$FPED_IND2, NHANES_20132014$NUTRIENT_IND2)
AHEI6 = AHEI_NHANES_FPED(NHANES_20152016$FPED_IND, NHANES_20152016$NUTRIENT_IND, NHANES_20152016$FPED_IND2, NHANES_20152016$NUTRIENT_IND2)
```

#AHEI数据合并
```{r}
AHEI <- Full_Join(AHEI1, AHEI2, AHEI3, AHEI4, AHEI5, AHEI6,
                  by = c("SEQN","AHEI_ALL"), 
                  cat = TRUE, 
                  inspect = NULL)
AHEI <- select_col(AHEI,c("SEQN","AHEI_ALL"))
```

# DII 
```{r}
DII1 = DII_NHANES_FPED(FPED_PATH=NHANES_20052006$FPED, NUTRIENT_PATH=NHANES_20052006$NUTRIENT, DEMO_PATH=NHANES_20052006$DEMO, FPED_PATH2=NHANES_20052006$FPED2, NUTRIENT_PATH2=NHANES_20052006$NUTRIENT2)
DII2 = DII_NHANES_FPED(FPED_PATH=NHANES_20072008$FPED, NUTRIENT_PATH=NHANES_20072008$NUTRIENT, DEMO_PATH=NHANES_20072008$DEMO, FPED_PATH2=NHANES_20072008$FPED2, NUTRIENT_PATH2=NHANES_20072008$NUTRIENT2)
DII3 = DII_NHANES_FPED(FPED_PATH=NHANES_20092010$FPED, NUTRIENT_PATH=NHANES_20092010$NUTRIENT, DEMO_PATH=NHANES_20092010$DEMO, FPED_PATH2=NHANES_20092010$FPED2, NUTRIENT_PATH2=NHANES_20092010$NUTRIENT2)
DII4 = DII_NHANES_FPED(FPED_PATH=NHANES_20112012$FPED, NUTRIENT_PATH=NHANES_20112012$NUTRIENT, DEMO_PATH=NHANES_20112012$DEMO, FPED_PATH2=NHANES_20112012$FPED2, NUTRIENT_PATH2=NHANES_20112012$NUTRIENT2)
DII5 = DII_NHANES_FPED(FPED_PATH=NHANES_20132014$FPED, NUTRIENT_PATH=NHANES_20132014$NUTRIENT, DEMO_PATH=NHANES_20132014$DEMO, FPED_PATH2=NHANES_20132014$FPED2, NUTRIENT_PATH2=NHANES_20132014$NUTRIENT2)
DII6 = DII_NHANES_FPED(FPED_PATH=NHANES_20152016$FPED, NUTRIENT_PATH=NHANES_20152016$NUTRIENT, DEMO_PATH=NHANES_20152016$DEMO, FPED_PATH2=NHANES_20152016$FPED2, NUTRIENT_PATH2=NHANES_20152016$NUTRIENT2)
```

#DII数据合并
```{r}
DII <- Full_Join(DII1, DII2, DII3, DII4, DII5, DII6,
                 by = c("SEQN","DII_ALL"), 
                 cat = TRUE, 
                 inspect = NULL)

DII <- select_col(DII,c("SEQN","DII_ALL"))
```

# HEI2020 
```{r}
HEI1 = HEI2020_NHANES_FPED(FPED_PATH=NHANES_20052006$FPED, NUTRIENT_PATH=NHANES_20052006$NUTRIENT, DEMO_PATH=NHANES_20052006$DEMO, FPED_PATH2=NHANES_20052006$FPED2, NUTRIENT_PATH2=NHANES_20052006$NUTRIENT2)
HEI2 = HEI2020_NHANES_FPED(FPED_PATH=NHANES_20072008$FPED, NUTRIENT_PATH=NHANES_20072008$NUTRIENT, DEMO_PATH=NHANES_20072008$DEMO, FPED_PATH2=NHANES_20072008$FPED2, NUTRIENT_PATH2=NHANES_20072008$NUTRIENT2)
HEI3 = HEI2020_NHANES_FPED(FPED_PATH=NHANES_20092010$FPED, NUTRIENT_PATH=NHANES_20092010$NUTRIENT, DEMO_PATH=NHANES_20092010$DEMO, FPED_PATH2=NHANES_20092010$FPED2, NUTRIENT_PATH2=NHANES_20092010$NUTRIENT2)
HEI4 = HEI2020_NHANES_FPED(FPED_PATH=NHANES_20112012$FPED, NUTRIENT_PATH=NHANES_20112012$NUTRIENT, DEMO_PATH=NHANES_20112012$DEMO, FPED_PATH2=NHANES_20112012$FPED2, NUTRIENT_PATH2=NHANES_20112012$NUTRIENT2)
HEI5 = HEI2020_NHANES_FPED(FPED_PATH=NHANES_20132014$FPED, NUTRIENT_PATH=NHANES_20132014$NUTRIENT, DEMO_PATH=NHANES_20132014$DEMO, FPED_PATH2=NHANES_20132014$FPED2, NUTRIENT_PATH2=NHANES_20132014$NUTRIENT2)
HEI6 = HEI2020_NHANES_FPED(FPED_PATH=NHANES_20152016$FPED, NUTRIENT_PATH=NHANES_20152016$NUTRIENT, DEMO_PATH=NHANES_20152016$DEMO, FPED_PATH2=NHANES_20152016$FPED2, NUTRIENT_PATH2=NHANES_20152016$NUTRIENT2)
```

# HEI2020数据合并
```{r}
HEI <- Full_Join(HEI1, HEI2, HEI3, HEI4, HEI5, HEI6,
                 by = c("SEQN","HEI2020_ALL"), 
                 cat = TRUE, 
                 inspect = NULL)

HEI <- select_col(HEI,c("SEQN","HEI2020_ALL"))
```

#四个饮食模型合并
```{r}
dp <- Full_Join(MED,AHEI,DII,HEI,by = "SEQN", cat = TRUE, inspect = NULL)

colnames(dp) <- c("seqn","med","ahei","dii","hei")

write.csv(dp,file = 'dp.csv')
```
