---
title: "敏感性分析"
author: "LA"
date: "2024-03-25"
output: html_document
---

```{r setup, include=FALSE}

setwd('E:/BaiduSyncdisk/R working directory/arthritis')

library(nhanesR)
library(dplyr)
library(survey)
```

# 数据分析

## 数据提取

人口学特征，BMI,吸烟饮酒等协变量提取

```{r}
demo <- nhs_tsv('demo_b|demo_c|demo_d|demo_e|demo_f|demo_g|demo_h|demo_i',years = 2005:2016)
bmx <- nhs_tsv('bmx_b|bmx_c|bmx_d|bmx_e|bmx_f|bmx_g|bmx_h|bmx_i',years = 2005:2016) 
smq <- nhs_tsv('smq_b|smq_c|smq_d|smq_e|smq_f|smq_g|smq_h|smq_i',years = 2005:2016)
alq <- nhs_tsv('alq_b|alq_c|alq_d|alq_e|alq_f|alq_g|alq_h|alq_i',years = 2005:2016)
cbc <- nhs_tsv('cbc_d|cbc_e|cbc_f|cbc_g|cbc_h|cbc_i',years = 2005:2016)
mcq <- nhs_tsv('mcq_d|mcq_e|mcq_f|mcq_g|mcq_h|mcq_i',years = 2005:2016)
```

合并协变量,膳食活性微生物，关节炎以及饮食权重数据

```{r}
p <- nhs_read(demo,
              'ridageyr:age',
              'riagendr:sex',
              'dmdeduc2:edu',
              'indfmpir:poverty',
              'dmdmartl:marital',
              'ridreth1:eth',
              bmx,'bmxbmi:bmi',
              smq,
              'smq020:smoke',
              alq,'ald100,alq101:alcohol',
                cbc,'lbdneno:neutrophil','lbxwbcsi:wbc',
              mcq,'mcq230A:mcq1','mcq230B:mcq2','mcq230C:mcq3','mcq230D:mcq4',
              codebook = TRUE)|>
  db_dr.live.microbes(years = 2005:2016,#膳食活性微生物
                        grams_Lo = TRUE,
                        grams_Med = TRUE,
                        grams_Hi = TRUE,
                        Year = TRUE)|>
    diag_arthritis(years= 2005:2016,#关节炎
                   arthritis = TRUE,
                   arghritis_type = TRUE,
                   Year = FALSE,
                   join = "left")|>
    db_drtot(years= 2005:2016,#饮食权重
             wtdr2d = TRUE,
             join = "left")
`
```

原始数据导出
```{r}
write.csv(p,file = 'p(sensitivity analysis).csv')
```

导入饮食模型数据并分组
```{r}
dp <- read.csv("dp.csv",header = T)
dp <- drop_col(dp,'X')
dp$medQ <- quant(dp$med, n = 5, Q = TRUE, round = 3)
dp$aheiQ <- quant(dp$ahei, n = 5, Q = TRUE, round = 3)
dp$diiQ <- quant(dp$dii, n = 5, Q = TRUE, round = 3)
dp$heiQ <- quant(dp$hei, n = 5, Q = TRUE, round = 3)
```

饮食模型数据合并

```{r}
p <- Full_Join(dp,p,by = "seqn", cat = TRUE, inspect = NULL)
```

## 数据清洗

去除权重缺失值和0

```{r}
p <- drop_row(p, is.na(p$wtdr2d))
p <- drop_row(p, p$wtdr2d == 0)
```

合并权重计算

```{r}
p$nhs_wt <- 1/6 * p$wtdr2d
```

选取18岁及以上的

```{r}
p <- drop_row(p,p$age<18)
```

重新编码，添加新列，判断关节炎类型

```{r}
p$arghritis_type <- paste0(p$arthritis,'~',p$arghritis_type)
p$arghritis_type <- Recode(p$arghritis_type,
                           "NA~NA::NA",
                           "no~NA::HC",
                           "yes~osteoarthritis::OA",
                           "yes~other::other",
                           "yes~rheumatoid arthritis::RA",
                           "yes~NA::NA",
                           "yes~psoriatic arthritis::other",
                           "yes~osteoarthritis or degenerative arthritis::OA",
                           to.numeric = FALSE)
```

去除关节炎缺失值

```{r}
p <- drop_row(p, is.na(p$arghritis_type)) 
```

去除膳食活性微生物缺失值

```{r}
p <- drop_row(p, is.na(p$grams_Lo)) 
p <- drop_row(p, is.na(p$grams_Med)) 
p <- drop_row(p, is.na(p$grams_Hi))
```

膳食活性微生物重新编码分组

```{r}
p <- p %>% newVb('microbe',
                 grams_Lo > 0 & grams_Hi == 0 & grams_Med == 0 ~'low',
                 grams_Med > 0 & grams_Hi == 0 ~ 'medium',
                 grams_Hi > 0 ~ 'high') 
p$microbe <- factor(p$microbe, levels = c('low','medium','high'))
```

重新分组编码，调整教育贫困婚姻种族BMI等协变量分组信息

```{r}
p$edu <- Recode(p$edu,
                "Less Than 9th Grade::Less than High School",
                "Less than 9th grade::Less than High School",
                "9-11th Grade (Includes 12th grade with no diploma)::Less than High School",
                "9-11th grade (Includes 12th grade with no diploma)::Less than High School",
                "High School Grad/GED or Equivalent::High School Grad",
                "High school graduate/GED or equivalent::High School Grad",
                "Some College or AA degree::Above High School",
                "Some college or AA degree::Above High School",
                "College Graduate or above::Above High School",
                "College graduate or above::Above High School",
                "Refused::NA",
                "Don't Know::NA",
                "NA::NA",
                to.numeric = FALSE)
p$marital <- Recode(p$marital,
                    "Married::Married/Living with partner",
                    "Living with partner::Married/Living with partner",
                    "Widowed::Widowed/Divorced/Separated",
                    "Divorced::Widowed/Divorced/Separated",
                    "Separated::Widowed/Divorced/Separated",
                    "Never married::Never married",
                    "Refused::NA",
                    "Don't know::NA",
                    to.numeric = FALSE)
p$eth <- Recode(p$eth,
                "Mexican American::Mexican American",
                "Other Hispanic::Other",
                "Other Race - Including Multi-Racial::Other",
                to.numeric = FALSE)
p <- p %>% newVb('povertynew',
                 poverty < 1.31 ~ 'low',
                 poverty <=3.5 ~ 'medium',
                 poverty > 3.5 ~ 'high')
p <- p %>% newVb('bminew',
                bmi < 25 ~ 'normal',
                 bmi <30 ~ 'overweight',
                 bmi >= 30 ~ 'obese')
p$marital <- factor(p$marital, levels = c('Married/Living with partner','Widowed/Divorced/Separated','Never married'))
p$povertynew <- factor(p$povertynew, levels = c('low','medium','high'))
p$bminew <- factor(p$bminew, levels = c('normal','overweight','obese'))
```

去除消化道肿瘤(胃癌，结直肠癌)
```{r}
p <- drop_row(p,p$mcq1 == 'Colon')
p <- drop_row(p,p$mcq2 == 'Colon')
p <- drop_row(p,p$mcq3 == 'Colon')
p <- drop_row(p,p$mcq4 == 'Colon')
p <- drop_row(p,p$mcq1 == 'Rectum (rectal)')
p <- drop_row(p,p$mcq2 == 'Rectum (rectal)')
p <- drop_row(p,p$mcq3 == 'Rectum (rectal)')
p <- drop_row(p,p$mcq4 == 'Rectum (rectal)')
p <- drop_row(p,p$mcq1 == 'Stomach')
p <- drop_row(p,p$mcq2 == 'Stomach')
p <- drop_row(p,p$mcq3 == 'Stomach')
p <- drop_row(p,p$mcq4 == 'Stomach')
```

去除协变量缺失值

```{r}
p <- drop_row(p, is.na(p$med))
p <- drop_row(p, is.na(p$ahei))
p <- drop_row(p, is.na(p$dii))
p <- drop_row(p, is.na(p$hei))
p <- drop_row(p, is.na(p$edu)) 
p <- drop_row(p, is.na(p$povertynew)) 
p <- drop_row(p, is.na(p$marital)) 
p <- drop_row(p, is.na(p$eth))
p <- drop_row(p, is.na(p$bminew)) 
p <- drop_row(p, is.na(p$smoke)) 
p <- drop_row(p, is.na(p$alcohol)) 
p <- drop_row(p, is.na(p$neutrophil))
p <- drop_row(p, is.na(p$wbc))
```

## 其他关节炎回归分析

赋值其他类型关节炎为1或0

```{r}
p$arghritis_typeother <- Recode(p$arghritis_type,
                             "OA::2",
                             "HC::0",
                             "other::1",
                             "RA::2",
                             to.numeric = TRUE)#数值型为true
p <- drop_row(p, p$arghritis_typeother == 2)
```

赋值后重新加权

```{r}
nhs <- svy_design(p)
```

### 膳食活性微生物单因素分析

```{r}
otu <- svy_uv.logit(design = nhs,
             y = 'arghritis_typeother',
             x = c('microbe'))
write.csv(otu,file = 'otu.csv')
```

### 膳食活性微生物多因素分析

调整模型1

```{r}
otm1 <- svyglm(arghritis_typeother ~ microbe + age + sex ,nhs,
       family = quasibinomial()) |>
    reg_table()
write.csv(otm1,file = 'otm1.csv')
```

调整模型2

```{r}
otm2 <- svyglm(arghritis_typeother ~ microbe + age + sex + bminew + smoke + alcohol,nhs,
       family = quasibinomial()) |>
    reg_table()
write.csv(otm2,file = 'otm2.csv')
```

调整模型3

```{r}
otm3 <- svyglm(arghritis_typeother ~ microbe + age + sex + edu + povertynew + eth + marital+ bminew + smoke + alcohol ,nhs,
       family = quasibinomial()) |>
    reg_table()
write.csv(otm3,file = 'otm3.csv')
```

调整模型4

```{r}
otm4 <- svyglm(arghritis_typeother ~ microbe + age + sex + edu + povertynew + eth + marital + bminew + smoke + alcohol+ medQ + aheiQ + diiQ + heiQ+neutrophil+wbc ,nhs, family = quasibinomial()) |>
    reg_table()
write.csv(otm4,file = 'otm4.csv')
```
